classdef TargetPoseRequest < robotics.ros.Message
    %TargetPoseRequest MATLAB implementation of irob_dvrk_automation/TargetPoseRequest
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2017 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'irob_dvrk_automation/TargetPoseRequest' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '1099465a71e86f47f3232d25b7cd9f21' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant)
        DISSECTION = int8(1)
        DISTANT = int8(2)
    end
    
    properties (Dependent)
        TargetType
    end
    
    properties (Constant, Hidden)
        PropertyList = {'TargetType'} % List of non-constant message properties
        ROSPropertyList = {'target_type'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = TargetPoseRequest(msg)
            %TargetPoseRequest Construct the message object TargetPoseRequest
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function targettype = get.TargetType(obj)
            %get.TargetType Get the value for property TargetType
            targettype = int8(obj.JavaMessage.getTargetType);
        end
        
        function set.TargetType(obj, targettype)
            %set.TargetType Set the value for property TargetType
            validateattributes(targettype, {'numeric'}, {'nonempty', 'scalar'}, 'TargetPoseRequest', 'TargetType');
            
            obj.JavaMessage.setTargetType(targettype);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.TargetType = obj.TargetType;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.TargetType = strObj.TargetType;
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.TargetType = obj.TargetType;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.irob_dvrk_automation.TargetPoseRequest.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.irob_dvrk_automation.TargetPoseRequest;
            obj.reload(strObj);
        end
    end
end
