instrument:
 name: 'Large suturecut needle driver'
 basic_type: GRIPPER
 jaw_length: 11.0
 jaw_parts:
  p0:
   start: 0.0
   end: 3.0
   type: JOINT
  p1:
   start: 3.0
   end: 5.0
   type: SCISSORS
  p2:
   start: 5.0
   end: 11.0
   type: GRIPPER
