# Dimensions are unaccurate, the jaws move in the direction
# of the axis aproximately 2 mm while opening
instrument:
 name: 'Null forceps'
 basic_type: GRIPPER
 jaw_length: 0.0
 jaw_parts:
  p0:
   start: 0.0
   end: 0.0
   type: GRIPPER
