# Define the goal
# Action types
int8 GO_TO=1
int8 TOOL_CLOSE=2
int8 TOOL_OPEN=3
int8 IN_TCP_FORWARD=4
int8 IN_TCP_BACKWARD=5

int8 action

# Params
ToolPose target
ToolPose[] waypoints

float64 speed
float64 distance
float64 angle

int8 INTERPOLATION_LINEAR=1
int8 INTERPOLATION_BEZIER=2

int8 interpolation

---
# Define the result
ToolPose pose
string info
---
# Define a feedback message
ToolPose pose
string info

