# Define the goal
int8 LINEAR=1
int8 BEZIER=2

ToolPose target
ToolPose[] waypoints
int8 interpolation

---
# Define the result
ToolPose pose
string info
---
# Define a feedback message
ToolPose pose
string info

