# Define the goal
# Action types
int8 STOP=1
int8 GO_TO=2
int8 GRASP=3
int8 CUT=4
int8 RELESE=5
int8 OPEN_JAWS=6
int8 APPROACH=7
int8 LEAVE=8


int8 action

# Params
ToolPose target
ToolPose[] waypoints

float64 speed
geometry_msgs/Point movement
float64 angle

int8 INTERPOLATION_LINEAR=1
int8 INTERPOLATION_BEZIER=2

int8 interpolation

---
# Define the result
ToolPose pose
string info
---
# Define a feedback message
ToolPose pose
string info

