function [BW,maskedRGBImage, centroid] = detectGrabLocation(RGB)
%createMask  Threshold RGB image using auto-generated code from colorThresholder app.
%  [BW,MASKEDRGBIMAGE] = createMask(RGB) thresholds image RGB using
%  auto-generated code from the colorThresholder App. The colorspace and
%  minimum/maximum values for each channel of the colorspace were set in the
%  App and result in a binary mask BW and a composite image maskedRGBImage,
%  which shows the original RGB image values under the mask BW.

% Auto-generated by colorThresholder app on 16-Nov-2017
%------------------------------------------------------


% Convert RGB image to chosen color space
I = rgb2hsv(RGB);

% Define thresholds for channel 1 based on histogram settings
channel1Min = 0.980;
channel1Max = 0.020;

% Define thresholds for channel 2 based on histogram settings
channel2Min = 0.174;
channel2Max = 0.995;

% Define thresholds for channel 3 based on histogram settings
channel3Min = 0.559;
channel3Max = 1.000;

% Create mask based on chosen histogram thresholds
sliderBW = ( (I(:,:,1) >= channel1Min) | (I(:,:,1) <= channel1Max) ) & ...
    (I(:,:,2) >= channel2Min ) & (I(:,:,2) <= channel2Max) & ...
    (I(:,:,3) >= channel3Min ) & (I(:,:,3) <= channel3Max);
BW = sliderBW;

% Initialize output masked image based on input image.
maskedRGBImage = RGB;

% Set background pixels where BW is false to zero.


se = strel('disk',3);
BW = imclose(BW,se);

BW = bwareafilt(BW,1);

s = regionprops(BW,'centroid');

centroid = cat(1, s.Centroid);

maskedRGBImage(repmat(~BW,[1 1 3])) = 0;

end
