classdef Marker < ros.Message
    %Marker MATLAB implementation of irob_msgs/Marker
    %   This class was automatically generated by
    %   ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2019 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'irob_msgs/Marker' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '780778cdd28b7aa01b2a2fea45187451' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        IrobMsgsPoint2DClass = ros.msg.internal.MessageFactory.getClassForType('irob_msgs/Point2D') % Dispatch to MATLAB class for message type irob_msgs/Point2D
    end
    
    properties (Dependent)
        Id
        Corners
    end
    
    properties (Access = protected)
        Cache = struct('Corners', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Corners', 'Id'} % List of non-constant message properties
        ROSPropertyList = {'corners', 'id'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = Marker(msg)
            %Marker Construct the message object Marker
            import com.mathworks.toolbox.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('ros:mlros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('ros:mlros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('ros:mlros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function id = get.Id(obj)
            %get.Id Get the value for property Id
            id = int8(obj.JavaMessage.getId);
        end
        
        function set.Id(obj, id)
            %set.Id Set the value for property Id
            validateattributes(id, {'numeric'}, {'nonempty', 'scalar'}, 'Marker', 'Id');
            
            obj.JavaMessage.setId(id);
        end
        
        function corners = get.Corners(obj)
            %get.Corners Get the value for property Corners
            if isempty(obj.Cache.Corners)
                javaArray = obj.JavaMessage.getCorners;
                array = obj.readJavaArray(javaArray, obj.IrobMsgsPoint2DClass);
                obj.Cache.Corners = feval(obj.IrobMsgsPoint2DClass, array);
            end
            corners = obj.Cache.Corners;
        end
        
        function set.Corners(obj, corners)
            %set.Corners Set the value for property Corners
            if ~isvector(corners) && isempty(corners)
                % Allow empty [] input
                corners = feval([obj.IrobMsgsPoint2DClass '.empty'], 0, 1);
            end
            
            validateattributes(corners, {obj.IrobMsgsPoint2DClass}, {'vector'}, 'Marker', 'Corners');
            
            javaArray = obj.JavaMessage.getCorners;
            array = obj.writeJavaArray(corners, javaArray, obj.IrobMsgsPoint2DClass);
            obj.JavaMessage.setCorners(array);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Corners)
                obj.Cache.Corners = [];
                obj.Cache.Corners = obj.Corners;
            end
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.Corners = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.Id = obj.Id;
            
            % Recursively copy compound properties
            cpObj.Corners = copy(obj.Corners);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Id = strObj.Id;
            CornersCell = arrayfun(@(x) feval([obj.IrobMsgsPoint2DClass '.loadobj'], x), strObj.Corners, 'UniformOutput', false);
            obj.Corners = vertcat(CornersCell{:});
        end
    end
    
    methods (Access = ?ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Id = obj.Id;
            strObj.Corners = arrayfun(@(x) saveobj(x), obj.Corners);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.custom.msggen.irob_msgs.Marker.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = ros.custom.msggen.irob_msgs.Marker;
            obj.reload(strObj);
        end
    end
end
