# Define the goal
string arm_name
float64 open_angle
geometry_msgs/Pose[] waypoints
geometry_msgs/Pose target
float64 approach_dist
float64 closed_angle

---
# Define the result
float64 angle
geometry_msgs/Pose pose
string info
---
# Define a feedback message
float64 angle
geometry_msgs/Pose pose
string info

