# offset board_t: [-26.0, 0.0, 13.0]

# board_t: [106.0, -3.0, 18.0]

board_t: [0.0, 0.0, 0.0]

peg_positions: [    25.0, 6.0, 0,
                    8.4, 20.0, 0,
                    42.0, 20.0, 0,
                    8.4, 42.8, 0,
                    42.0, 42.8, 0,
                    25.0, 56.8, 0,

                    60.0, 13.5, 0,
                    89.1, 13.5, 0,
                    60.0, 31.2, 0,
                    89.1, 31.2, 0,
                    60.0, 49.0, 0,
                    89.1, 49.0, 0]

peg_h: 26.5

object_h: 15.0

object_d: 15.0

object_wall_d: 2.0
#
