# offset board_t: [-26.0, 0.0, 13.0]

# board_t: [106.0, -3.0, 18.0]

board_t: [0.0, 0.0, 0.0]

peg_positions: [    25.0, -6.0, 0,
                    8.4, -20.0, 0,
                    42.0, -20.0, 0,
                    8.4, -42.8, 0,
                    42.0, -42.8, 0,
                    25.0, -56.8, 0,

                    56.0, -13.5, 0,
                    85.1, -15.5, 0,
                    56.0, -31.2, 0,
                    85.1, -33.2, 0,
                    56.0, -49.0, 0,
                    85.1, -51.0, 0]

grasp_positions: [  -2.45  , 3.5455, 0,
                    2.1   , 3.5455, 0,
                    4.55  , 0.0455, 0,
                    2.625 ,  -3.4545, 0,
                    -2.1   ,  -3.4545, 0,
                    -4.2   , 0.0455, 0]

park_position:    [100.0 , 30.0, -100.0]

peg_h: 46.0
tool_l: 20.0

sag_h: 7.0

object_h: 15.0

object_d: 15.0

object_wall_d: 2.0
#
