# offset board_t: [-26.0, 0.0, 13.0]

# board_t: [106.0, -3.0, 18.0]

board_t: [0.0, 0.0, 0.0]

peg_positions: [    17.7, 20.3, 0,
                    6.4, 33.0, 0,
                    30.0, 33.0, 0,
                    6.4, 49.0, 0,
                    30.0, 49.0, 0,
                    16.7, 60.0, 0,

                    42.5, 21.2, 0,
                    67.7, 21.2, 0,
                    42.5, 41.2, 0,
                    67.7, 41.2, 0,
                    42.5, 61.2, 0,
                    67.7, 61.2, 0]

peg_h: 20.0

object_h: 33.0

object_d: 12.0

object_wall_d: 2.0
#
