

model_3d_pegs: [18.7, 17.3, 0,
                    9.4, 28.0, 0,
                    31.0, 28.0, 0,
                    9.4, 46.0, 0,
                    31.0, 46.0, 0,
                    21.7, 57.0, 0,

                    43.5, 17.2, 0,
                    68.7, 17.2, 0,
                    43.5, 37.2, 0,
                    68.7, 37.2, 0,
                    43.5, 57.2, 0,
                    68.7, 57.2, 0]

target_h: 60.0

grasp_h: 20.0

target_d: 2.0

