# offset board_t: [-26.0, 0.0, 13.0]

board_t: [106.0, -3.0, 18.0]

peg_positions: [    19.7, 18.3, 0,
                    9.4, 31.0, 0,
                    33.0, 31.0, 0,
                    9.4, 47.0, 0,
                    33.0, 47.0, 0,
                    19.7, 58.0, 0,

                    42.5, 20.2, -3.0,
                    67.7, 20.2, -3.0,
                    42.5, 40.2, -3.0,
                    67.7, 40.2, -3.0,
                    42.5, 60.2, -3.0,
                    67.7, 60.2, -3.0]

peg_h: 20.0

object_h: 33.0

object_d: 12.0

object_wall_d: 2.0

