classdef GetControlVariablesResponse < robotics.ros.Message
    %GetControlVariablesResponse MATLAB implementation of irob_msgs/GetControlVariablesResponse
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2018 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'irob_msgs/GetControlVariablesResponse' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = 'de49712f644e9355d79ea9349cc9c04d' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Dependent)
        Output
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Output'} % List of non-constant message properties
        ROSPropertyList = {'output'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = GetControlVariablesResponse(msg)
            %GetControlVariablesResponse Construct the message object GetControlVariablesResponse
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function output = get.Output(obj)
            %get.Output Get the value for property Output
            javaArray = obj.JavaMessage.getOutput;
            array = obj.readJavaArray(javaArray, 'double');
            output = double(array);
        end
        
        function set.Output(obj, output)
            %set.Output Set the value for property Output
            if ~isvector(output) && isempty(output)
                % Allow empty [] input
                output = double.empty(0,1);
            end
            
            validateattributes(output, {'numeric'}, {'vector'}, 'GetControlVariablesResponse', 'Output');
            
            javaArray = obj.JavaMessage.getOutput;
            array = obj.writeJavaArray(output, javaArray, 'double');
            obj.JavaMessage.setOutput(array);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.Output = obj.Output;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Output = strObj.Output;
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Output = obj.Output;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.irob_msgs.GetControlVariablesResponse.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.irob_msgs.GetControlVariablesResponse;
            obj.reload(strObj);
        end
    end
end
