classdef InstrumentJawPart < robotics.ros.Message
    %InstrumentJawPart MATLAB implementation of irob_msgs/InstrumentJawPart
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2017 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'irob_msgs/InstrumentJawPart' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = 'b8cbfa0714c905135198fc20d37c8fc5' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant)
        JOINT = int8(1)
        GRIPPER = int8(2)
        SCISSORS = int8(3)
    end
    
    properties (Dependent)
        Type
        Start
        End
    end
    
    properties (Constant, Hidden)
        PropertyList = {'End', 'Start', 'Type'} % List of non-constant message properties
        ROSPropertyList = {'end', 'start', 'type'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = InstrumentJawPart(msg)
            %InstrumentJawPart Construct the message object InstrumentJawPart
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function type = get.Type(obj)
            %get.Type Get the value for property Type
            type = int8(obj.JavaMessage.getType);
        end
        
        function set.Type(obj, type)
            %set.Type Set the value for property Type
            validateattributes(type, {'numeric'}, {'nonempty', 'scalar'}, 'InstrumentJawPart', 'Type');
            
            obj.JavaMessage.setType(type);
        end
        
        function start = get.Start(obj)
            %get.Start Get the value for property Start
            start = double(obj.JavaMessage.getStart);
        end
        
        function set.Start(obj, start)
            %set.Start Set the value for property Start
            validateattributes(start, {'numeric'}, {'nonempty', 'scalar'}, 'InstrumentJawPart', 'Start');
            
            obj.JavaMessage.setStart(start);
        end
        
        function end_ = get.End(obj)
            %get.End Get the value for property End
            end_ = double(obj.JavaMessage.getEnd);
        end
        
        function set.End(obj, end_)
            %set.End Set the value for property End
            validateattributes(end_, {'numeric'}, {'nonempty', 'scalar'}, 'InstrumentJawPart', 'End');
            
            obj.JavaMessage.setEnd(end_);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.Type = obj.Type;
            cpObj.Start = obj.Start;
            cpObj.End = obj.End;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Type = strObj.Type;
            obj.Start = strObj.Start;
            obj.End = strObj.End;
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Type = obj.Type;
            strObj.Start = obj.Start;
            strObj.End = obj.End;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.irob_msgs.InstrumentJawPart.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.irob_msgs.InstrumentJawPart;
            obj.reload(strObj);
        end
    end
end
